### ISSUE TITLE
Evaluation script error with TinyLlama

### ISSUE THREAD

**Issue by srikhetramohanty** [songmzhang/DSKD#12]
Hi @songmzhang  I tried running the evaluation shell script with TinyLlama and it threw the error : 
<img width="541" alt="image" src="https://github.com/user-attachments/assets/933953c2-acf9-46b3-af1a-f7139af6c353">

Any leads into what might be the issue here? Mistral checkpoint ran fine with this modified evaluation shell script. 

Note : 
MODEL_PATH="/---/---/DSKD/model_hub/tinyllama/tinyllama-1.1b-3T"

Terminal command : 
`bash scripts/tinyllama/eval_sample.sh $”/---/---/DSKD/outputs/tinyllama/tinyllama-1.1b-3T/sft/criterion=cross_entropy__lora-rank=256-alpha=8-dropout=0.1-bf16__epoch=10__bsz=8x1x1=8__lr=0.001/epoch10_step14300_loss2.2730_rougel27.6927” $16
`

**Comment by songmzhang** [comment]
Hi, this is because we missed adding the tokenizer class of TinyLLama to the `def get_tokenizer()` in `utils.py`. Now we have fixed this bug and you can pull the latest code version.

**Comment by srikhetramohanty** [comment]
Thanks. It worked.
