### ISSUE TITLE
GPT2-1.5B Pretrained Teacher on Dolly

### ISSUE THREAD

**Issue by cpsu00** [songmzhang/DSKD#17]
Hello, I'm not sure where is the GPT2-1.5B pretrained teacher on dolly is located in the link in readme. Can you guide me where to find it?

**Comment by songmzhang** [comment]
For this model, we directly use the checkpoint released by Gu et al. in MiniLLM. The link in readme points to the repo of MiniLLM.
![image](https://github.com/user-attachments/assets/a7ce45b3-9afd-4791-9516-9d0c55bbe2e0)
You can download the gpt2 models via the provided commands. Then untar the `gpt2.tar` and you will find it in `gpt2/train/sft/gpt2-xlarge`.

**Comment by cpsu00** [comment]
It works! Thanks for your fast reply.
