### ISSUE TITLE
Failed to reproduce KD results

### ISSUE THREAD

**Issue by cpsu00** [songmzhang/DSKD#18]
Hello,

I was trying to reproduce the KD results in the paper, but the results I got are somewhat worse than the reported results.

Additionally, I noticed that both MiniLLM and DistiLLM have different KD results as well.

I suspect that the difference in hardware (I'm using a single RTX 4090) might be influencing the results, but I’m not certain. Could you take a look at my results and let me know if they seem reasonable?

<img width="165" alt="image" src="https://github.com/user-attachments/assets/c0805eea-39e1-4d53-9898-a6e7878b1f02">

**Comment by songmzhang** [comment]
The results on Dolly, SelfInst, and VicunaEval look ok, but the ones on S-NI and UnNI are slightly lower. Could you provide your training log and script for KD? And have you reproduced the SFT results? Does KD get better results than SFT?

**Comment by cpsu00** [comment]
Thanks for your fast reply. 
Here are the training and evaluation logs. The script is generally the same as vanilla_kd_gpt2_base.sh with the first line change to  `GPUS=(0)`. 
I'm currently trying another run, I'll try to reproduce SFT once it's complete.

[train.log](https://github.com/user-attachments/files/16959799/train.log)
[log.txt](https://github.com/user-attachments/files/16959797/log.txt)

**Comment by songmzhang** [comment]
> Thanks for your fast reply. Here are the training and evaluation logs. The script is generally the same as vanilla_kd_gpt2_base.sh with the first line change to `GPUS=(0)`. I'm currently trying another run, I'll try to reproduce SFT once it's complete.
> 
> [train.log](https://github.com/user-attachments/files/16959799/train.log) [log.txt](https://github.com/user-attachments/files/16959797/log.txt)

One probable reason is the **batchsize**. In our experiments, we fix the global batchsize (n_gpus x batch_size_per_gpu x gradient_accumulation_steps) to 32 for all experiments. In your case, if you set one gpu and set batch_size_per_gpu to 4, you should increase the `--gradient_accumulation_steps` from 2 to 8.

**Comment by cpsu00** [comment]
It works! Thank you.
