### ISSUE TITLE
Files for token mapping

### ISSUE THREAD

**Issue by ntsw2001** [songmzhang/DSKD#20]
Dear authors, I noticed that the loss you provided through the `distiller.py` involves json files containing the mapping relationship between the token and token_id of the teacher model and the student model. Files mentioned above come from https://github.com/songmzhang/DSKD#data , which follow the path `/data/vocab_alignment` . Well, how such files are generated? Or, in other words, how is your implementation of the mapping relationship file similar to or different from FuseLLM's work?

作者们您好，注意到你们在 `distiller.py` 文件中，读取了包含教师模型和学生模型的 token 和 token_id 的之间的映射关系 json 文件（文件下载于：https://github.com/songmzhang/DSKD#data ，在压缩包路径的 `/data/vocab_alignment` 中）。想请教一下，这些文件是如何生成的？或者说，映射关系文件的生成上与 FuseLLM 的工作又有何异同？

**Comment by songmzhang** [comment]
Hi! Actually, all the files in `/data/vocab_alignment` were generated by [vocab_alignment.py](https://github.com/18907305772/FuseAI/blob/110fff4c32c69d408ee769d696b002e691afd20b/FuseLLM/src/utils/vocab_mapping.py) from FuseLLM.

As shown in the directories, you may notice that the mapping files have two directions, i.e., student->teacher and teacher->student, which represent the most similar teacher (student) token for each student (teacher) token. These two directions are obtained by swapping the teacher and the student vocabularies when running [vocab_alignment.py](https://github.com/18907305772/FuseAI/blob/110fff4c32c69d408ee769d696b002e691afd20b/FuseLLM/src/utils/vocab_mapping.py). And actually we just use teacher->student mapping in our code like FuseLLM.

**Comment by ntsw2001** [comment]
That's great. Thanks a lot for your reply!
