### ISSUE TITLE
From where should we downloads the models?

### ISSUE THREAD

**Issue by survivebycoding** [songmzhang/DSKD#4]
In huggingface there are different versions of the model, can you share the URL of the model file from where you had downloaded them?

**Comment by songmzhang** [comment]
Sure! I will update the relevant URLs in README.md.

**Comment by survivebycoding** [comment]
Thank you so much! if you can attach the url of all the models you tried , will be useful

**Comment by songmzhang** [comment]
> Thank you so much! if you can attach the url of all the models you tried , will be useful

Hi! Please check README.md to obtain the urls of all the models used in our paper.

**Comment by survivebycoding** [comment]
Thank you so much!
