### ISSUE TITLE
Can we use this code for CPU?

### ISSUE THREAD

**Issue by survivebycoding** [songmzhang/DSKD#6]
Can we change this code 
`GPUS=(0)
export CUDA_VISIBLE_DEVICES=$(IFS=,; echo "${GPUS[*]}")`

to  `CUDA_VISIBLE_DEVICES=""` to use CPUs?

**Comment by songmzhang** [comment]
It may not directly support CPU since we implement the training process with DDP. You may need to modify the `distillation.py` by yourself to train models on the CPU.
