### ISSUE TITLE
More desctipion on output folder created

### ISSUE THREAD

**Issue by survivebycoding** [songmzhang/DSKD#7]
Once SFT is run on a model, output folder gets created. 
Is it possible to add some explanation towards the structure of output folder that got created, like what all files are expected to be generated and what each file means, etc? This will add to the readability of the readme file.

**Comment by songmzhang** [comment]
Sure. We've added the corresponding explanation in README.md. Please refer to [this line](https://github.com/songmzhang/DSKD/blob/main/README.md#file-structures-in-output-directory).
