### ISSUE TITLE
Getting an error when trying to perform SFT on Tiny Llama

### ISSUE THREAD

**Issue by survivebycoding** [songmzhang/DSKD#8]
We are getting this error when trying to execute SFT on TinyLlama:
`[rank0]:     if f.read(7) == "version":
[rank0]:   File "/usr/lib/python3.10/codecs.py", line 322, in decode
[rank0]:     (result, consumed) = self._buffer_decode(data, self.errors, final)
[rank0]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 70: invalid start byte`

However, we found no issue executing llama and mistral. If you have any idea regarding this issue, please let us know

**Comment by songmzhang** [comment]
It is due to the version of `transformers` library. We also found this issue in our early experiments. The version suggested by TinyLLaMA is 4.31, while we loaded it with transformers == 4.38 and also found this error.

We conjecture that it may be because some weights of LlamaForCausalLM were not initialized from the model checkpoint.

Here is our solution:
1. Create another environment with transformers == 4.31 
2. Load the model checkpoint and re-save it into another directory (noted as `tinyllama_new`), i.e., `model = AutoModelForCausalLM.from_pretrained(original_tinyllama_path)` and `model.save_pretrained(tinyllama_new, safe_serialization=False)`.
3. Switch to the original environment for this project and load the model checkpoint from `tinyllama_new`.

**Comment by songmzhang** [comment]
Thanks for reminding us of this issue and we will add this to README.md.

**Comment by survivebycoding** [comment]
original_tinyllama_path - is this the path in our system where we have downloaded tiny llama?

**Comment by songmzhang** [comment]
> original_tinyllama_path - is this the path in our system where we have downloaded tiny llama?

Yes.

**Comment by survivebycoding** [comment]
original_tinyllama_path - will this be the path of the bin? which one should the path be?
![image](https://github.com/user-attachments/assets/be691f65-b285-4e8d-b429-61d1c2694be0)

**Comment by survivebycoding** [comment]
![image](https://github.com/user-attachments/assets/0a1323b3-8032-4bce-ad7d-c0e66d0416e7)
The new llama folder created does not have the same files.

Getting the error" 
[OSError: Can't load tokenizer for '/tinyllama/tinyllama-1.1b-3T'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/tinyllama/tinyllama-1.1b-3T' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.]

**Comment by songmzhang** [comment]
> ![image](https://private-user-images.githubusercontent.com/37393147/354968682-0a1323b3-8032-4bce-ad7d-c0e66d0416e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MzM2MDYsIm5iZiI6MTcyMjgzMzMwNiwicGF0aCI6Ii8zNzM5MzE0Ny8zNTQ5Njg2ODItMGExMzIzYjMtODAzMi00YmNlLWFkN2QtYzBlNjZkMDQxNmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA0NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYWQ0YmI1ZmFhNDkyYjRlZjM1NzUzZGI3M2YxZjIxOTgxYWRkOTQ4NzNiMWRlNWNkOTgxZDlmNThhOWNlZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vSVW2_56Ak1wmMB5_Eom-u-N_pMgZJGPVLWCIVA4Vts) The new llama folder created does not have the same files.
> 
> Getting the error" [OSError: Can't load tokenizer for '/tinyllama/tinyllama-1.1b-3T'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/tinyllama/tinyllama-1.1b-3T' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.]

You need to copy tokenizer files (i.e., special_tokens_map.json, tokenizer_config.json, tokenizer.json, tokenizer.model) to the new directory to load the tokenizer.

**Comment by survivebycoding** [comment]
Full finetuning eval scripts 
![image](https://github.com/user-attachments/assets/0b4a0242-23c2-46a6-a1a1-dc80fb824bbc)
are under gpt2 folder of scripts and for lora its under tiny llama scripts? Or is lora only applicable to tiny llama?

This part is a bit confusing, maybe you can clarify a bit what ckpt_path and lora_adapter_path is.... also, what is usually given in eval_batch_size?

**Comment by survivebycoding** [comment]
In vanilla_KD_tinyllama [TEACHER_PEFT_PATH="path_to_teacher_sft_lora_ckpt"]
is the path to the folder called epoch9 right?
![image](https://github.com/user-attachments/assets/8cda45c5-afbf-4e96-9e10-2ad45298e95a)

**Comment by songmzhang** [comment]
> Full finetuning eval scripts ![image](https://private-user-images.githubusercontent.com/37393147/355065125-0b4a0242-23c2-46a6-a1a1-dc80fb824bbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQ3NzUsIm5iZiI6MTcyMjg1NDQ3NSwicGF0aCI6Ii8zNzM5MzE0Ny8zNTUwNjUxMjUtMGI0YTAyNDItMjNjMi00NmE2LWExYTEtZGM4MGZiODI0YmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEwNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMmU3NDVhMmExNDBlODYwY2E2YmIwMjRiNTAxOTVmNzE5NWQzNDAwODllMzU2M2E1OTM4ZTgxNzc0NDZiNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ym-t9hDFJsr-FXHXlK6CHPNSUxl7b-wRG3Gz4Soz00U) are under gpt2 folder of scripts and for lora its under tiny llama scripts? Or is lora only applicable to tiny llama?
> 
> This part is a bit confusing, maybe you can clarify a bit what ckpt_path and lora_adapter_path is.... also, what is usually given in eval_batch_size?

No, `run_eval_lora.sh` is not only applicable to TinyLLaMA. The scripts and README.md are just for re-implementing the experiments in our paper. Actually, you can also evaluate other fully fine-tuned checkpoints besides GPT2 with `run_eval.sh`.

Here, `CKPT_PATH` means the path of the full fine-tuned checkpoint. For example, in your case, it is the path of "epoch9_step...".

Similarly, `LORA_ADAPTER_PATH` is the path of the LoRA adapter, whose name has the same format as the full fine-tuned ckpt like "epoch9_step...".

For `EVAL_BATCH_SIZE`, it depends on the available GPU memory and the amount of the model parameters. For example, we use 32 for GPT2-base and 8 for TinyLLaMA.

**Comment by songmzhang** [comment]
> In vanilla_KD_tinyllama [TEACHER_PEFT_PATH="path_to_teacher_sft_lora_ckpt"] is the path to the folder called epoch9 right? ![image](https://private-user-images.githubusercontent.com/37393147/355067182-8cda45c5-afbf-4e96-9e10-2ad45298e95a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQ3NzUsIm5iZiI6MTcyMjg1NDQ3NSwicGF0aCI6Ii8zNzM5MzE0Ny8zNTUwNjcxODItOGNkYTQ1YzUtYWZiZi00ZTk2LTllMTAtMmFkNDUyOThlOTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEwNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZDA3MTJiZDZlNmM4NjAzYWU4NTg1ZWJhZTQxZWI0NzZhZWI5NTY3YTI3NDYzMjlhYWMyZGE2MjljYThlNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m3KJMobQiV9We0fEnwAEESo1BHKLieTNMsJDIc8eKRw)

Yes.
